**House Prices - Advanced Regression Techniques**

Predict sales prices and practice feature engineering, RFs, and gradient boosting. This project aims to predict the sales price for each house. For each Id in the test set, the value of the SalePrice variable must be predicted.

In [1]:
#import python libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
#load the dataset for the project
df = pd.read_csv("C:/Users/user/OneDrive/Documents/Data Science Projects/ML projects/House Price - Advanced Regression Techniques/train.csv",
                encoding = "latin")

DATA EXPLORATION AND PREPROCESSING

In [5]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [6]:
df.tail()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [7]:
df.shape

(1460, 81)

In [8]:
df.info() #display the info about the dataset

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     1452 non-null   object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [9]:
df_num = df.select_dtypes(include = {int, float}) #display the columns that are numerical in nature
df_num.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold', 'SalePrice'],
      dtype='object')

In [10]:
len(df.select_dtypes(include = {int, float}).columns) #find the number of the numerical columns

38

In [11]:
df_cat = df.select_dtypes(exclude = {int, float}) #display the columns that are categorical in nature
df_cat.columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [12]:
len(df.select_dtypes(exclude = {int,float}).columns) #find the number of the categorical columns

43

In [13]:
df_num.isna().sum() #check for missing values in numerical columns

Id                 0
MSSubClass         0
LotFrontage      259
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea         8
BsmtFinSF1         0
BsmtFinSF2         0
BsmtUnfSF          0
TotalBsmtSF        0
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       0
BsmtHalfBath       0
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       81
GarageCars         0
GarageArea         0
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
SalePrice          0
dtype: int64

In [14]:
df_num["LotFrontage"].fillna(-999, inplace = True) #fill the na with value -999
df_num["GarageYrBlt"].fillna(-999, inplace = True)
df_num["MasVnrArea"].fillna(-999, inplace = True)

In [15]:
df_num.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,-119.596575,10516.828082,6.099315,5.575342,1971.267808,1984.865753,97.643151,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,409.115115,9981.264932,1.382997,1.112799,30.202904,20.645407,198.080250,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,-999.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,-999.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,42.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,63.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,79.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,164.250000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [16]:
df_cat.isna().sum() #check for missing values in categorical columns

MSZoning            0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinType2       38
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
KitchenQual         0
Functional          0
FireplaceQu       690
GarageType         81
GarageFinish       81
GarageQual         81
GarageCond         81
PavedDrive          0
PoolQC           1453
Fence            1179
MiscFeature      1406
SaleType            0
SaleCondition       0
dtype: int64

In [17]:
#drop the categorical columns with missing values
df_cnew = df_cat.drop(columns = ['MiscFeature', 'Fence', 'PoolQC', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
                               'GarageCond', 'Electrical', 'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
                               'MasVnrType', 'Alley'])
len(df_cnew.columns) #display the new length of categorical variaables

27

In [18]:
df_cat['MiscFeature'].fillna(df_cat['MiscFeature'].mode(), inplace = True)
df_cat['Fence'].fillna(df_cat['Fence'].mode(), inplace = True)
df_cat['PoolQC'].fillna(df_cat['PoolQC'].mode(), inplace = True)
df_cat['FireplaceQu'].fillna(df_cat['FireplaceQu'].mode(), inplace = True)
df_cat['GarageType'].fillna(df_cat['GarageType'].mode(), inplace = True)
df_cat['GarageFinish'].fillna(df_cat['GarageFinish'].mode(), inplace = True)
df_cat['GarageQual'].fillna(df_cat['GarageQual'].mode(), inplace = True)
df_cat['GarageCond'].fillna(df_cat['GarageCond'].mode(), inplace = True)
df_cat['Electrical'].fillna(df_cat['Electrical'].mode(), inplace = True)
df_cat['BsmtQual'].fillna(df_cat['BsmtQual'].mode(), inplace = True)
df_cat['BsmtCond'].fillna(df_cat['BsmtCond'].mode(), inplace = True)
df_cat['BsmtExposure'].fillna(df_cat['BsmtExposure'].mode(), inplace = True)
df_cat['BsmtFinType1'].fillna(df_cat['BsmtFinType1'].mode(), inplace = True)
df_cat['BsmtFinType2'].fillna(df_cat['BsmtFinType2'].mode(), inplace = True)
df_cat['MasVnrType'].fillna(df_cat['MasVnrType'].mode(), inplace = True)
df_cat['Alley'].fillna(df_cat['Alley'].mode(), inplace = True)

In [19]:
df_cnew.isna().sum().sum()

0

In [20]:
df_c1new = pd.get_dummies(df_cnew) #encoded the categorical variables using pd.get_dummies
df_c1new.head()

,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Grvl,Street_Pave,LotShape_IR1,LotShape_IR2,LotShape_IR3,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,1,0,0,1,0,0,0,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,1,0,0,0,0,0
4,0,0,0,1,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0

In [21]:
dff = pd.concat([df_num, df_c1new], axis = 1)
dff.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,65.0,8450,7,5,2003,2003,196.0,706,...,0,0,0,1,0,0,0,0,1,0
1,2,20,80.0,9600,6,8,1976,1976,0.0,978,...,0,0,0,1,0,0,0,0,1,0
2,3,60,68.0,11250,7,5,2001,2002,162.0,486,...,0,0,0,1,0,0,0,0,1,0
3,4,70,60.0,9550,7,5,1915,1970,0.0,216,...,0,0,0,1,1,0,0,0,0,0
4,5,60,84.0,14260,8,5,2000,2000,350.0,655,...,0,0,0,1,0,0,0,0,1,0

In [22]:
dff.isna().sum()

Id                       0
MSSubClass               0
LotFrontage              0
LotArea                  0
OverallQual              0
                        ..
SaleCondition_AdjLand    0
SaleCondition_Alloca     0
SaleCondition_Family     0
SaleCondition_Normal     0
SaleCondition_Partial    0
Length: 220, dtype: int64

In [23]:
df_num.corr()['SalePrice'].sort_values(ascending = False)

SalePrice        1.000000
OverallQual      0.790982
GrLivArea        0.708624
GarageCars       0.640409
GarageArea       0.623431
TotalBsmtSF      0.613581
1stFlrSF         0.605852
FullBath         0.560664
TotRmsAbvGrd     0.533723
YearBuilt        0.522897
YearRemodAdd     0.507101
Fireplaces       0.466929
MasVnrArea       0.411879
BsmtFinSF1       0.386420
WoodDeckSF       0.324413
2ndFlrSF         0.319334
OpenPorchSF      0.315856
HalfBath         0.284108
LotArea          0.263843
GarageYrBlt      0.253221
BsmtFullBath     0.227122
BsmtUnfSF        0.214479
BedroomAbvGr     0.168213
ScreenPorch      0.111447
PoolArea         0.092404
MoSold           0.046432
3SsnPorch        0.044584
LotFrontage      0.013948
BsmtFinSF2      -0.011378
BsmtHalfBath    -0.016844
MiscVal         -0.021190
Id              -0.021917
LowQualFinSF    -0.025606
YrSold          -0.028923
OverallCond     -0.077856
MSSubClass      -0.084284
EnclosedPorch   -0.128578
KitchenAbvGr    -0.135907
Name: SalePrice, dtype: float64

In [24]:
dff.corr()['SalePrice'].sort_values(ascending = False)

SalePrice            1.000000
OverallQual          0.790982
GrLivArea            0.708624
GarageCars           0.640409
GarageArea           0.623431
                       ...
MSZoning_RM         -0.288065
HeatingQC_TA        -0.312677
Foundation_CBlock   -0.343263
KitchenQual_TA      -0.519298
ExterQual_TA        -0.589044
Name: SalePrice, Length: 220, dtype: float64

In [25]:
correlation_matrix = dff.corr()

# Filter correlations above 0.7
high_correlation = correlation_matrix[correlation_matrix > 0.6]
high_correlation

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
Id,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MSSubClass,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LotFrontage,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
LotArea,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OverallQual,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
SaleCondition_AdjLand,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
SaleCondition_Alloca,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
SaleCondition_Family,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
SaleCondition_Normal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,0.634322,NaN,NaN,NaN,NaN,1.0,NaN
SaleCondition_Partial,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.986819,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [26]:
#dff1 = dff.drop(['SaleType_New', 'SaleType_WD'], axis = 1)

In [27]:
dff.corr()['SalePrice'].sort_values(ascending = False)

SalePrice            1.000000
OverallQual          0.790982
GrLivArea            0.708624
GarageCars           0.640409
GarageArea           0.623431
                       ...
MSZoning_RM         -0.288065
HeatingQC_TA        -0.312677
Foundation_CBlock   -0.343263
KitchenQual_TA      -0.519298
ExterQual_TA        -0.589044
Name: SalePrice, Length: 220, dtype: float64

In [28]:
correlation_with_target = dff.corr()['SalePrice']
strong_positive_correlation_features = correlation_with_target[correlation_with_target >= 0.1].index
strong_negative_correlation_features = correlation_with_target[correlation_with_target <= -0.1].index

In [29]:
strong_correlation_features = strong_positive_correlation_features.union(strong_negative_correlation_features)
df_fil = dff[strong_correlation_features]
df_fil.corr()['SalePrice'].sort_values(ascending = False)

SalePrice            1.000000
OverallQual          0.790982
GrLivArea            0.708624
GarageCars           0.640409
GarageArea           0.623431
                       ...
MSZoning_RM         -0.288065
HeatingQC_TA        -0.312677
Foundation_CBlock   -0.343263
KitchenQual_TA      -0.519298
ExterQual_TA        -0.589044
Name: SalePrice, Length: 96, dtype: float64

In [30]:
df_fil.columns

Index(['1stFlrSF', '2ndFlrSF', 'BedroomAbvGr', 'BldgType_1Fam',
       'BldgType_Duplex', 'BsmtFinSF1', 'BsmtFullBath', 'BsmtUnfSF',
       'CentralAir_N', 'CentralAir_Y', 'Condition1_Artery', 'Condition1_Feedr',
       'Condition1_Norm', 'EnclosedPorch', 'ExterCond_Fa', 'ExterCond_TA',
       'ExterQual_Ex', 'ExterQual_Fa', 'ExterQual_Gd', 'ExterQual_TA',
       'Exterior1st_AsbShng', 'Exterior1st_CemntBd', 'Exterior1st_MetalSd',
       'Exterior1st_VinylSd', 'Exterior1st_Wd Sdng', 'Exterior2nd_CmentBd',
       'Exterior2nd_MetalSd', 'Exterior2nd_VinylSd', 'Exterior2nd_Wd Sdng',
       'Fireplaces', 'Foundation_BrkTil', 'Foundation_CBlock',
       'Foundation_PConc', 'Foundation_Slab', 'FullBath', 'Functional_Typ',
       'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea', 'HalfBath',
       'HeatingQC_Ex', 'HeatingQC_Fa', 'HeatingQC_Gd', 'HeatingQC_TA',
       'HouseStyle_1.5Fin', 'HouseStyle_2Story', 'KitchenAbvGr',
       'KitchenQual_Ex', 'KitchenQual_Fa', 'KitchenQual_Gd', 'KitchenQual_TA',
       'LandContour_Bnk', 'LandContour_HLS', 'LotArea', 'LotConfig_CulDSac',
       'LotShape_IR1', 'LotShape_IR2', 'LotShape_Reg', 'MSZoning_C (all)',
       'MSZoning_RL', 'MSZoning_RM', 'MasVnrArea', 'Neighborhood_BrDale',
       'Neighborhood_BrkSide', 'Neighborhood_Edwards', 'Neighborhood_IDOTRR',
       'Neighborhood_MeadowV', 'Neighborhood_NAmes', 'Neighborhood_NoRidge',
       'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'Neighborhood_Sawyer',
       'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber',
       'OpenPorchSF', 'OverallQual', 'PavedDrive_N', 'PavedDrive_Y',
       'RoofMatl_CompShg', 'RoofMatl_WdShngl', 'RoofStyle_Gable',
       'RoofStyle_Hip', 'SaleCondition_Abnorml', 'SaleCondition_Normal',
       'SaleCondition_Partial', 'SalePrice', 'SaleType_New', 'SaleType_WD',
       'ScreenPorch', 'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd'],
      dtype='object')

In [31]:
len(df_fil.columns)

96

BUILDING THE MACHINE LEARNING MODEL USING LINEAR REGRESSION

In [53]:
#import machine learning libraries
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import Ridge, Lasso
from sklearn.ensemble import RandomForestRegressor

In [33]:
#display the features and target variables for splitting
X = df_fil.drop(['SalePrice'], axis = 1)
y = df_fil['SalePrice']

In [34]:
X.columns

Index(['1stFlrSF', '2ndFlrSF', 'BedroomAbvGr', 'BldgType_1Fam',
       'BldgType_Duplex', 'BsmtFinSF1', 'BsmtFullBath', 'BsmtUnfSF',
       'CentralAir_N', 'CentralAir_Y', 'Condition1_Artery', 'Condition1_Feedr',
       'Condition1_Norm', 'EnclosedPorch', 'ExterCond_Fa', 'ExterCond_TA',
       'ExterQual_Ex', 'ExterQual_Fa', 'ExterQual_Gd', 'ExterQual_TA',
       'Exterior1st_AsbShng', 'Exterior1st_CemntBd', 'Exterior1st_MetalSd',
       'Exterior1st_VinylSd', 'Exterior1st_Wd Sdng', 'Exterior2nd_CmentBd',
       'Exterior2nd_MetalSd', 'Exterior2nd_VinylSd', 'Exterior2nd_Wd Sdng',
       'Fireplaces', 'Foundation_BrkTil', 'Foundation_CBlock',
       'Foundation_PConc', 'Foundation_Slab', 'FullBath', 'Functional_Typ',
       'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea', 'HalfBath',
       'HeatingQC_Ex', 'HeatingQC_Fa', 'HeatingQC_Gd', 'HeatingQC_TA',
       'HouseStyle_1.5Fin', 'HouseStyle_2Story', 'KitchenAbvGr',
       'KitchenQual_Ex', 'KitchenQual_Fa', 'KitchenQual_Gd', 'KitchenQual_TA',
       'LandContour_Bnk', 'LandContour_HLS', 'LotArea', 'LotConfig_CulDSac',
       'LotShape_IR1', 'LotShape_IR2', 'LotShape_Reg', 'MSZoning_C (all)',
       'MSZoning_RL', 'MSZoning_RM', 'MasVnrArea', 'Neighborhood_BrDale',
       'Neighborhood_BrkSide', 'Neighborhood_Edwards', 'Neighborhood_IDOTRR',
       'Neighborhood_MeadowV', 'Neighborhood_NAmes', 'Neighborhood_NoRidge',
       'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'Neighborhood_Sawyer',
       'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber',
       'OpenPorchSF', 'OverallQual', 'PavedDrive_N', 'PavedDrive_Y',
       'RoofMatl_CompShg', 'RoofMatl_WdShngl', 'RoofStyle_Gable',
       'RoofStyle_Hip', 'SaleCondition_Abnorml', 'SaleCondition_Normal',
       'SaleCondition_Partial', 'SaleType_New', 'SaleType_WD', 'ScreenPorch',
       'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd'],
      dtype='object')

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42, test_size = 0.2) #splitted the dataset

In [36]:
scale = StandardScaler()
X_train_scaled = scale.fit_transform(X_train)
X_test_scaled = scale.transform(X_test)

In [37]:
model = LinearRegression()
model.fit(X_train_scaled, y_train) #fit the linear regression model

LinearRegression()

In [38]:
y_pred = model.predict(X_test_scaled) #predict the target variable using the test dataset
y_pred

array([138199.89352624, 324543.6157932 ,  99058.90320696, 166869.83935479,
       319650.30873034,  78980.0134664 , 225977.2429439 , 138468.54110403,
        71713.16319699, 139884.13409279, 153028.87163689, 118322.54362351,
        98767.44742939, 230069.38537968, 173364.78224873, 135374.27987948,
       198767.10547913, 134620.50230519,  95909.57488587, 214145.92515434,
       183866.50836191, 209932.39824791, 183268.8542321 , 131073.99246505,
       200157.11820056, 146554.94025046, 197604.78376218, 115036.73785183,
       173134.37444128, 195353.47368709, 119944.47898445, 288293.73028259,
       244360.13237467,  96881.16003968, 256062.53823712, 148515.85388988,
       149840.07158033, 208468.59953838, 325551.61620212,  91403.48925665,
       130384.41417431, 237494.14214654, 111877.23330768, 350634.8861098 ,
       141769.44045975, 156152.47674291, 107923.07607244, 122816.70180997,
       387333.22764547, 122576.40425489, 111943.38591108, 212726.35496817,
        93009.72332956, 254796.80741384, 149045.2081688 , 228668.57836223,
       213975.57238076, 186097.75203998, 136495.7582163 ,  92926.24882695,
        64756.14561895, 153404.18284255, 296512.28720622, 281616.78691211,
       279295.33073657, 200311.62709696,  95276.76998817, 277651.74297435,
       113895.15057453, 161971.23480598, 115740.03009821, 114241.24927147,
       101136.07458226,  78242.0310375 , 424647.59994041, 217249.05004385,
       314121.30220676, 311374.89039863, 137744.7656723 ,  97087.97237061,
       104509.50305204,  80001.74894454, 140180.7720368 ,  79351.59376481,
       146688.82753872, 129793.78125836, 257894.26253513, 206772.31391285,
       144961.79276802, 200799.68487189, 123629.30720921, 163029.0997941 ,
       114590.19285483, 258481.16043735, 116626.68726598, 182031.12238744,
       214138.9958995 , 190995.80415879, 209315.75937157, 277044.86891789,
       144699.64381421, 210982.31375419, 252917.14326931, 140268.8730641 ,
       167900.3493887 , 187329.09546503, 150049.03221578, 286376.25254329,
       145342.36585321, 218606.21532897,  71972.30117356, 151330.20729424,
       134688.36460499, 122639.79370888, 200452.78797754, 119211.88266706,
        91485.11297239, 127440.30630626, 137490.92936445, 281956.39462201,
       122054.24476309, 145180.14107418, 192284.57700649, 201985.52411991,
       189284.47145192, 141431.86821676, 229593.25473321,  82079.58895717,
       138520.39331039, 193962.3801271 , 188429.35825902, 298973.26280012,
       192959.22170951, 156254.60044648,  16572.26896538, 364633.729298  ,
       362329.50332634, 145586.37883598, 226215.32613049, 547484.12320755,
       363594.99249692, 124028.53969431, 182199.38081295, 168709.90383214,
       126682.18384472, 124255.80023283, 212715.35464525, 196947.80749818,
       115698.96692663,  63321.49903035, 122672.0697894 , 135752.90942451,
       251047.65896431, 147046.22666585,  86603.6848116 , 122754.18862155,
       125294.23591013, 146913.37355147,  85104.68304114, 129387.79293113,
       191291.50239496, 127857.43316492, 291296.98904793, 122129.32984525,
       118523.30796571, 108210.93395709, 246507.77724163, 306167.5864396 ,
       389917.13883491, 220848.31573394, 354220.21111848,  91666.84469976,
       112517.54747592, 161170.65201153, 323715.70340796, 115336.30180406,
       132519.18028239, 231346.60233393, 135499.94971723, 170355.6255852 ,
       155508.08727535,  96864.99711011, 129826.77535773, 153079.37340661,
       242214.55877344, 124310.16458533, 274763.32776791, 228361.47554351,
       222700.99767223,  67951.80632003, 119134.07189829,  93056.49691506,
       162659.8173812 , 150096.65089162, 216943.45237101, 193682.1864702 ,
       206374.3458201 ,  59835.96054251, 210803.07387121, 134553.99556233,
       285024.11768406, 220312.23489039, 119206.1786918 , 318786.54006909,
       198169.66328372, 121167.76109927, 227674.51735447, 123772.66883973,
       148223.14260006, 100846.3452886 , 226691.6040849 , 156811.07701149,
       131274.41386631, 156065.89907918, 192858.65282899, 243686.80066023,
       191478.27601686, 135040.86795349, 116307.0178603 , 144452.31635065,
       144494.8461734 , 243576.07481503, 182667.98351183,  86438.94208583,
       238668.08505414, 141022.46804271,  83028.68631013,  93187.97844061,
       148408.48907282,  87173.01948072,  97816.42094452, 171951.65846595,
       123563.6518197 , 112250.1596345 , 229789.74489813, 135305.2611609 ,
       209918.00111032, 163959.58270695, 233915.65231436, 119743.1432376 ,
       108851.06312842, 254664.21319965, 205257.05685518, 442925.51040155,
       192606.28623614,  97904.74189717,  98513.39408604, 180152.44720215,
       126789.66317518, 105608.14529737, 140661.08486923, 200137.98032083,
       147790.19999103, 108149.91637969, 144792.39528165, 137657.43632079,
        90325.50114818, 110136.4121439 , 180541.34197034, 245374.24146021,
       299599.58110244, 174887.34272647, 127853.55424195, 247277.88884661,
       343752.03014658, 232575.76790718, 170669.80081138, 142763.9360643 ,
       118339.25590932, 200949.69253088, 396293.99700753, 252399.41002252,
       232183.08351514,  80270.86941322,  99546.71094209, 135300.56366043,
       131146.74426223, 322359.58256898, 231721.75282315, 121437.17243072,
       203865.41308717, 118111.03743495, 211493.78045409, 104235.78943629,
       260051.18734685, 163625.31040634, 211867.64648335,  99180.37042375,
       274320.2505681 , 198566.83068526,  94882.98715221, 108908.23076382])

In [39]:
log_y_test = np.log(y_test) #calculated the logarithmic value of predicted value and the observed sales price.
log_y_pred = np.log(y_pred)

In [40]:
mae = mean_absolute_error(log_y_test, log_y_pred) #calculated the metric - Mean Absolute Error
mae

0.1107310303111843

In [41]:
mse = mean_squared_error(log_y_test, log_y_pred) #calculated the metric - Mean Squared Error
rmse = np.sqrt(mse)
rmse

0.1505167124891687

**LASSO REGRESSION MODEL**

In [50]:
alpha = 1.0  # Regularization strength (hyperparameter)
lasso = Lasso(alpha=alpha)
lasso.fit(X_train_scaled, y_train)

# Make predictions
y_pred_test = lasso.predict(X_test_scaled)
y_pred_test

C:\Users\user\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.370e+10, tolerance: 6.967e+08
  model = cd_fast.enet_coordinate_descent(

array([138201.79055849, 324588.05077376,  98989.56059681, 166821.23828828,
       319579.94323782,  78964.35491056, 225960.68198005, 138504.83960641,
        71692.55945004, 139902.98411989, 153053.27460117, 118334.95583816,
        98853.92302597, 230085.00783425, 173401.64146389, 135326.99207829,
       198760.89835898, 134547.92142705,  95864.47283247, 214117.26652995,
       183859.50521597, 209956.86588479, 183288.73269411, 131028.23388404,
       200162.20267631, 146589.33128177, 197582.85171918, 114989.73815154,
       173155.86980135, 195461.76332855, 119959.03090996, 288302.89728588,
       244283.73818848,  96858.36383434, 256083.69281069, 148533.1753958 ,
       149893.51020982, 208479.5947676 , 325560.2361042 ,  91409.59109162,
       130549.14690705, 237513.05140858, 111607.21804533, 350797.62189402,
       141763.03008268, 156249.20842588, 107886.64364308, 122844.77999095,
       387385.59807875, 122523.89227547, 111910.26657233, 212698.18686203,
        93097.24032792, 254749.61343993, 149085.94163422, 228655.30292941,
       213951.6189523 , 186031.6958152 , 136539.31188388,  92920.30986852,
        64688.60110725, 153368.56435137, 296550.89158997, 281608.77769227,
       279304.52349956, 200316.05777971,  95264.4345692 , 277620.76864088,
       113952.4997555 , 161995.30149035, 115719.46731003, 114240.94950347,
       101075.97574673,  78201.66317686, 424674.60359044, 217257.49847947,
       314168.36562155, 311412.16953752, 137720.53251767,  97003.89481309,
       104481.08425749,  79918.34340057, 140176.39485958,  79330.05100228,
       146720.19668978, 129874.08965605, 257933.04316246, 206741.16059482,
       144992.17292831, 200802.98525583, 123723.43082155, 162826.47404696,
       114564.17470748, 258434.28278178, 116726.33385812, 181986.42408659,
       214145.9678596 , 191022.37126233, 209304.71412736, 276973.54990594,
       144831.46884374, 210988.99983123, 252868.57572553, 140329.29350165,
       167873.22325674, 187323.56697019, 149994.8326816 , 286316.77102719,
       145322.55117181, 218683.27245266,  72106.37862827, 151338.96953447,
       134731.13835128, 122725.35407324, 200455.59926411, 119202.76956948,
        91446.02460556, 127330.34388886, 137522.89845687, 281963.84590397,
       122121.70973379, 145210.31341583, 192337.65208832, 201967.0960496 ,
       189182.58646267, 141423.96631881, 229577.13555669,  82142.80156904,
       138558.08165596, 193990.8229564 , 188411.81481774, 298907.06193775,
       192945.13720874, 156325.59915455,  16585.98122368, 364636.53854593,
       362425.63909453, 145577.50719994, 226217.51885507, 547481.66747973,
       363608.4680922 , 123976.22115539, 182184.57927165, 168618.91388089,
       126615.72639162, 124294.22448939, 212641.60608274, 196919.40195423,
       115669.53012593,  63370.9473457 , 122707.3078125 , 135725.46359199,
       251000.657608  , 147062.16506503,  86513.38736935, 122892.14144992,
       125343.28629827, 146917.53736768,  85145.84024609, 129383.89749986,
       191291.32118205, 127962.82972107, 291253.91797839, 122150.39229697,
       118488.90743473, 108282.88384213, 246481.07545712, 306135.20105982,
       389835.135302  , 220808.18177981, 354228.19161556,  91641.38366208,
       112632.16226888, 161191.29644165, 323756.27292525, 115349.82015021,
       132568.72147895, 231218.75325255, 135382.29113424, 170366.28897184,
       155495.6426253 ,  96848.38952355, 129744.60352815, 153140.39515812,
       242217.09427366, 124205.21958067, 274699.8565292 , 228379.97120619,
       222785.4880131 ,  67979.89751848, 119113.61412364,  93100.91126874,
       162772.95105242, 150134.10485942, 217012.40939729, 193522.06452817,
       206402.38753246,  59743.46205537, 210827.45821026, 134583.72782766,
       284987.21632143, 220278.53808012, 119131.57020525, 318819.72694514,
       198167.68993829, 121158.97721075, 227662.99861425, 123820.25410803,
       147950.03124081, 100850.27196365, 226583.22673226, 156847.74161283,
       131248.44802053, 156086.15986602, 192770.96739709, 243712.45378709,
       191597.81792583, 135132.31129968, 116237.0252569 , 144536.89457633,
       144490.26563814, 243602.99922739, 182571.06539906,  86418.27594554,
       238621.35166851, 140964.8920042 ,  83004.85176402,  93273.33266598,
       148330.00925854,  87347.56027163,  97751.68702203, 171893.22591224,
       123529.8322701 , 112222.18806304, 229768.01647877, 135365.98348303,
       209917.70645097, 163934.31296933, 233859.52229696, 119776.50180523,
       108895.84504905, 254552.34737145, 205141.73573522, 442903.37395768,
       192582.46377232,  97955.21467525,  98567.11344423, 180013.00448174,
       126858.00097372, 105055.73468838, 140886.02783204, 200057.05000174,
       147829.07662359, 108193.40919554, 144803.26798322, 137687.41821871,
        90246.58545331, 110110.67235829, 180549.89857632, 245378.21889499,
       299633.53551175, 174896.52417613, 127854.63332776, 247206.25659064,
       343743.91169218, 232511.86395028, 170699.27621223, 142776.99102912,
       118388.00070903, 200896.70291835, 396356.62312492, 252450.2451894 ,
       232202.6996084 ,  80306.45410703,  99578.89212584, 135291.56291478,
       131181.13980206, 322454.70628601, 231125.93571678, 121387.99869177,
       203868.45534746, 118057.19463566, 211519.63740397, 104313.18953576,
       260022.29436611, 163501.57735598, 211871.59251987,  99178.10235724,
       274271.90347569, 198555.03899204,  94879.26887078, 108867.79583395])

In [51]:
log_y_test = np.log(y_test) #calculated the logarithmic value of predicted value and the observed sales price.
log_y_predn = np.log(y_pred_test)

In [52]:
mse_lasso = mean_squared_error(log_y_test, log_y_predn) #calculated the metric - Mean Squared Error
rmse = np.sqrt(mse_lasso)
rmse

0.15049504620981796

**RANDOM FOREST MODEL**

In [59]:
log_y_test = np.log(y_test) #calculated the logarithmic value of predicted value and the observed sales price.
log_y_predn = np.log(y_pred_test_rf)

In [60]:
n_estimators = 100  # Number of trees in the forest (hyperparameter)
max_depth = None  # Maximum depth of the trees (hyperparameter)
random_forest = RandomForestRegressor(n_estimators=n_estimators, max_depth=max_depth)
random_forest.fit(X_train_scaled, y_train)

# Make predictions
y_pred_test_rf = random_forest.predict(X_test_scaled)

# Evaluate the model
mse_test = mean_squared_error(log_y_test, log_y_predn)
mse_test

0.023298291126290793

In [61]:
rmse = np.sqrt(mse_test)
rmse

0.15263777752014995

**TEST THE BUILT MODEL USING THE TESTING DATASET**

In [39]:
td = pd.read_csv("C:/Users/user/OneDrive/Documents/Data Science Projects/House Price - Advanced Regression Techniques/test.csv", 
                encoding = "latin")

In [69]:
td.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,Grvl,Reg,Lvl,AllPub,...,120,0,Ex,MnPrv,Shed,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,Ex,MnPrv,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,Ex,MnPrv,Shed,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,Grvl,IR1,Lvl,AllPub,...,0,0,Ex,MnPrv,Shed,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,Grvl,IR1,HLS,AllPub,...,144,0,Ex,MnPrv,Shed,0,1,2010,WD,Normal

In [41]:
len(td.columns)

80

DATA PREPROCESSING

In [42]:
td.isna().sum()

Id                 0
MSSubClass         0
MSZoning           4
LotFrontage      227
LotArea            0
                ...
MiscVal            0
MoSold             0
YrSold             0
SaleType           1
SaleCondition      0
Length: 80, dtype: int64

In [43]:
td_num = td.select_dtypes(include = {int, float})
td_num.columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtUnfSF', 'TotalBsmtSF', '1stFlrSF', '2ndFlrSF',
       'LowQualFinSF', 'GrLivArea', 'BsmtFullBath', 'BsmtHalfBath', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'KitchenAbvGr', 'TotRmsAbvGrd',
       'Fireplaces', 'GarageYrBlt', 'GarageCars', 'GarageArea', 'WoodDeckSF',
       'OpenPorchSF', 'EnclosedPorch', '3SsnPorch', 'ScreenPorch', 'PoolArea',
       'MiscVal', 'MoSold', 'YrSold'],
      dtype='object')

In [44]:
td_cat = td.select_dtypes(exclude = {int, float})
td_cat.columns

Index(['MSZoning', 'Street', 'Alley', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [45]:
td_num.isna().sum()

Id                 0
MSSubClass         0
LotFrontage      227
LotArea            0
OverallQual        0
OverallCond        0
YearBuilt          0
YearRemodAdd       0
MasVnrArea        15
BsmtFinSF1         1
BsmtFinSF2         1
BsmtUnfSF          1
TotalBsmtSF        1
1stFlrSF           0
2ndFlrSF           0
LowQualFinSF       0
GrLivArea          0
BsmtFullBath       2
BsmtHalfBath       2
FullBath           0
HalfBath           0
BedroomAbvGr       0
KitchenAbvGr       0
TotRmsAbvGrd       0
Fireplaces         0
GarageYrBlt       78
GarageCars         1
GarageArea         1
WoodDeckSF         0
OpenPorchSF        0
EnclosedPorch      0
3SsnPorch          0
ScreenPorch        0
PoolArea           0
MiscVal            0
MoSold             0
YrSold             0
dtype: int64

In [46]:
td_num["LotFrontage"].fillna(-999, inplace = True)
td_num["GarageArea"].fillna(-999, inplace = True)
td_num["GarageCars"].fillna(-999, inplace = True)
td_num["GarageYrBlt"].fillna(-999, inplace = True)
td_num["BsmtHalfBath"].fillna(-999, inplace = True)
td_num["BsmtFullBath"].fillna(-999, inplace = True)
td_num["TotalBsmtSF"].fillna(-999, inplace = True)
td_num["BsmtUnfSF"].fillna(-999, inplace = True)
td_num["BsmtFinSF2"].fillna(-999, inplace = True)
td_num["BsmtFinSF1"].fillna(-999, inplace = True)
td_num["MasVnrArea"].fillna(-999, inplace = True)

In [47]:
td_num.isna().sum().sum()

0

In [48]:
td_cat.isna().sum()

MSZoning            4
Street              0
Alley            1352
LotShape            0
LandContour         0
Utilities           2
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
RoofStyle           0
RoofMatl            0
Exterior1st         1
Exterior2nd         1
MasVnrType         16
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           44
BsmtCond           45
BsmtExposure       44
BsmtFinType1       42
BsmtFinType2       42
Heating             0
HeatingQC           0
CentralAir          0
Electrical          0
KitchenQual         1
Functional          2
FireplaceQu       730
GarageType         76
GarageFinish       78
GarageQual         78
GarageCond         78
PavedDrive          0
PoolQC           1456
Fence            1169
MiscFeature      1408
SaleType            1
SaleCondition       0
dtype: int64

In [49]:
td_cat['SaleType'].fillna(td_cat['SaleType'].mode()[0], inplace = True)
td_cat['MiscFeature'].fillna(td_cat['MiscFeature'].mode()[0], inplace = True)
td_cat['Fence'].fillna(td_cat['Fence'].mode()[0], inplace = True)
td_cat['PoolQC'].fillna(td_cat['PoolQC'].mode()[0], inplace = True)
td_cat['GarageType'].fillna(td_cat['GarageType'].mode()[0], inplace = True)
td_cat['GarageFinish'].fillna(td_cat['GarageFinish'].mode()[0], inplace = True)
td_cat['GarageQual'].fillna(td_cat['GarageQual'].mode()[0], inplace = True)
td_cat['GarageCond'].fillna(td_cat['GarageCond'].mode()[0], inplace = True)
td_cat['FireplaceQu'].fillna(td_cat['FireplaceQu'].mode()[0], inplace = True)
td_cat['Functional'].fillna(td_cat['Functional'].mode()[0], inplace = True)
td_cat['KitchenQual'].fillna(td_cat['KitchenQual'].mode()[0], inplace = True)
td_cat['BsmtCond'].fillna(td_cat['BsmtCond'].mode()[0], inplace = True)
td_cat['BsmtExposure'].fillna(td_cat['BsmtExposure'].mode()[0], inplace = True)
td_cat['BsmtFinType1'].fillna(td_cat['BsmtFinType1'].mode()[0], inplace = True)
td_cat['BsmtFinType2'].fillna(td_cat['BsmtFinType2'].mode()[0], inplace = True)
td_cat['MasVnrType'].fillna(td_cat['MasVnrType'].mode()[0], inplace = True)
td_cat['Alley'].fillna(td_cat['Alley'].mode()[0], inplace = True)
td_cat['MSZoning'].fillna(td_cat['MSZoning'].mode()[0], inplace = True)
td_cat['Utilities'].fillna(td_cat['Utilities'].mode()[0], inplace = True)
td_cat['Exterior1st'].fillna(td_cat['Exterior1st'].mode()[0], inplace = True)
td_cat['Exterior2nd'].fillna(td_cat['Exterior2nd'].mode()[0], inplace = True)
td_cat['MasVnrType'].fillna(td_cat['MasVnrType'].mode()[0], inplace = True)
td_cat['BsmtQual'].fillna(td_cat['BsmtQual'].mode()[0], inplace = True)

In [50]:
td_cat.isna().sum().sum()

0

In [54]:
td_cnew = pd.get_dummies(td_cat) #encoded the categorical variables using pd.get_dummies
td_cnew.head()

,MSZoning_C (all),MSZoning_FV,MSZoning_RH,MSZoning_RL,MSZoning_RM,Street_Grvl,Street_Pave,Alley_Grvl,Alley_Pave,LotShape_IR1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,0,0,1,0,0,0,1,1,0,0,...,0,0,0,1,0,0,0,0,1,0
1,0,0,0,1,0,0,1,1,0,1,...,0,0,0,1,0,0,0,0,1,0
2,0,0,0,1,0,0,1,1,0,1,...,0,0,0,1,0,0,0,0,1,0
3,0,0,0,1,0,0,1,1,0,1,...,0,0,0,1,0,0,0,0,1,0
4,0,0,0,1,0,0,1,1,0,1,...,0,0,0,1,0,0,0,0,1,0

In [55]:
tdd = pd.concat([td_num, td_cnew], axis = 1) #concatenate the numerical and categorical columns into one
tdd.head()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1461,20,80.0,11622,5,6,1961,1961,0.0,468.0,...,0,0,0,1,0,0,0,0,1,0
1,1462,20,81.0,14267,6,6,1958,1958,108.0,923.0,...,0,0,0,1,0,0,0,0,1,0
2,1463,60,74.0,13830,5,5,1997,1998,0.0,791.0,...,0,0,0,1,0,0,0,0,1,0
3,1464,60,78.0,9978,6,6,1998,1998,20.0,602.0,...,0,0,0,1,0,0,0,0,1,0
4,1465,120,43.0,5005,8,5,1992,1992,0.0,263.0,...,0,0,0,1,0,0,0,0,1,0

In [68]:
tdd.columns #display the columns

Index(['Id', 'MSSubClass', 'LotFrontage', 'LotArea', 'OverallQual',
       'OverallCond', 'YearBuilt', 'YearRemodAdd', 'MasVnrArea', 'BsmtFinSF1',
       ...
       'SaleType_ConLw', 'SaleType_New', 'SaleType_Oth', 'SaleType_WD',
       'SaleCondition_Abnorml', 'SaleCondition_AdjLand',
       'SaleCondition_Alloca', 'SaleCondition_Family', 'SaleCondition_Normal',
       'SaleCondition_Partial'],
      dtype='object', length=271)

In [57]:
X_td = tdd[['1stFlrSF', '2ndFlrSF', 'BedroomAbvGr', 'BldgType_1Fam',
       'BldgType_Duplex', 'BsmtFinSF1', 'BsmtFullBath', 'BsmtUnfSF',
       'CentralAir_N', 'CentralAir_Y', 'Condition1_Artery', 'Condition1_Feedr',
       'Condition1_Norm', 'EnclosedPorch', 'ExterCond_Fa', 'ExterCond_TA',
       'ExterQual_Ex', 'ExterQual_Fa', 'ExterQual_Gd', 'ExterQual_TA',
       'Exterior1st_AsbShng', 'Exterior1st_CemntBd', 'Exterior1st_MetalSd',
       'Exterior1st_VinylSd', 'Exterior1st_Wd Sdng', 'Exterior2nd_CmentBd',
       'Exterior2nd_MetalSd', 'Exterior2nd_VinylSd', 'Exterior2nd_Wd Sdng',
       'Fireplaces', 'Foundation_BrkTil', 'Foundation_CBlock',
       'Foundation_PConc', 'Foundation_Slab', 'FullBath', 'Functional_Typ',
       'GarageArea', 'GarageCars', 'GarageYrBlt', 'GrLivArea', 'HalfBath',
       'HeatingQC_Ex', 'HeatingQC_Fa', 'HeatingQC_Gd', 'HeatingQC_TA',
       'HouseStyle_1.5Fin', 'HouseStyle_2Story', 'KitchenAbvGr',
       'KitchenQual_Ex', 'KitchenQual_Fa', 'KitchenQual_Gd', 'KitchenQual_TA',
       'LandContour_Bnk', 'LandContour_HLS', 'LotArea', 'LotConfig_CulDSac',
       'LotShape_IR1', 'LotShape_IR2', 'LotShape_Reg', 'MSZoning_C (all)',
       'MSZoning_RL', 'MSZoning_RM', 'MasVnrArea', 'Neighborhood_BrDale',
       'Neighborhood_BrkSide', 'Neighborhood_Edwards', 'Neighborhood_IDOTRR',
       'Neighborhood_MeadowV', 'Neighborhood_NAmes', 'Neighborhood_NoRidge',
       'Neighborhood_NridgHt', 'Neighborhood_OldTown', 'Neighborhood_Sawyer',
       'Neighborhood_Somerst', 'Neighborhood_StoneBr', 'Neighborhood_Timber',
       'OpenPorchSF', 'OverallQual', 'PavedDrive_N', 'PavedDrive_Y',
       'RoofMatl_CompShg', 'RoofMatl_WdShngl', 'RoofStyle_Gable',
       'RoofStyle_Hip', 'SaleCondition_Abnorml', 'SaleCondition_Normal',
       'SaleCondition_Partial', 'SaleType_New', 'SaleType_WD',
       'ScreenPorch', 'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd']]
X_td.head()

,1stFlrSF,2ndFlrSF,BedroomAbvGr,BldgType_1Fam,BldgType_Duplex,BsmtFinSF1,BsmtFullBath,BsmtUnfSF,CentralAir_N,CentralAir_Y,...,SaleCondition_Normal,SaleCondition_Partial,SaleType_New,SaleType_WD,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd
0,896,0,2,1,0,468.0,0.0,270.0,0,1,...,1,0,0,1,120,5,882.0,140,1961,1961
1,1329,0,3,1,0,923.0,0.0,406.0,0,1,...,1,0,0,1,0,6,1329.0,393,1958,1958
2,928,701,3,1,0,791.0,0.0,137.0,0,1,...,1,0,0,1,0,6,928.0,212,1997,1998
3,926,678,3,1,0,602.0,0.0,324.0,0,1,...,1,0,0,1,0,7,926.0,360,1998,1998
4,1280,0,2,0,0,263.0,0.0,1017.0,0,1,...,1,0,0,1,144,5,1280.0,0,1992,1992

In [67]:
X_testnew_scaled = scale.transform(X_td) #scale the new features

In [66]:
y_prednew = model.predict(X_testnew_scaled) #predict the new target variable using the test dataset
y_prednew

array([ 99809.07828336, 163288.53488614, 171263.19057176, ...,
       176368.81444037, 122432.81535676, 228494.1212636 ])

**UPLOAD THE DATAFRAME TO A CSV FILE AND SAVE TO MY COMPUTER**

In [72]:
submission_df = pd.DataFrame({'ID': td['Id'], 'SalePrice': y_prednew})

# Define the CSV file path
csv_file_path = 'C:/Users/user/OneDrive/Documents/Data Science Projects/ML projects/House Price - Advanced Regression Techniques/My submission.csv'

# Write the DataFrame to a CSV file
submission_df.to_csv(csv_file_path, index=False)

print("Submission file has been saved to", csv_file_path)

Submission file has been saved to C:/Users/user/OneDrive/Documents/Data Science Projects/ML projects/House Price - Advanced Regression Techniques/My submission.csv